SET REFERENTIAL_INTEGRITY FALSE;

SHOW TABLES;

TRUNCATE TABLE MANUFACTURER;

TRUNCATE TABLE INJECTOR_TYPE;

TRUNCATE TABLE VOLT_AMPERE_PROFILE;

TRUNCATE TABLE INJECTOR;

TRUNCATE TABLE TEST_NAME;

TRUNCATE TABLE INJECTOR_TEST;

TRUNCATE TABLE PARAMETERS;

TRUNCATE TABLE VALVES;

TRUNCATE TABLE NOZZLES;

TRUNCATE TABLE APPLICATIONS;

TRUNCATE TABLE CARS;

TRUNCATE TABLE SPARES;

TRUNCATE TABLE ENGINES;

TRUNCATE TABLE REFERENCE;

TRUNCATE TABLE DENSOINJECTORS;

TRUNCATE TABLE ISA_DETECTION;

-- PUMP_PARTITION

TRUNCATE TABLE MANUFACTURER_PUMP;

TRUNCATE TABLE PUMP;

TRUNCATE TABLE PUMP_TEST_NAME;

TRUNCATE TABLE PUMP_TEST;

TRUNCATE TABLE PUMP_INFO;

TRUNCATE TABLE PUMP_CAR_MODEL;

-- UIS_PARTITION

TRUNCATE TABLE MANUFACTURERS_UIS;

TRUNCATE TABLE INJECTORS_UIS;

TRUNCATE TABLE INJECTOR_TESTS_UIS;

TRUNCATE TABLE REFERENCE_UIS;

TRUNCATE TABLE TEST_NAMES_UIS;

TRUNCATE TABLE VOLT_AMPERE_PROFILES_UIS;

SET REFERENTIAL_INTEGRITY TRUE;