SET REFERENTIAL_INTEGRITY FALSE;

SHOW TABLES;

TRUNCATE TABLE MANUFACTURER;

TRUNCATE TABLE INJECTOR_TYPE;

TRUNCATE TABLE VOLT_AMPERE_PROFILE;

TRUNCATE TABLE INJECTOR;

TRUNCATE TABLE TEST_NAME;

TRUNCATE TABLE INJECTOR_TEST;

TRUNCATE TABLE ISA_DETECTION;

SET REFERENTIAL_INTEGRITY TRUE;