SET REFERENTIAL_INTEGRITY FALSE;

SHOW TABLES;

TRUNCATE TABLE MANUFACTURER;

TRUNCATE TABLE INJECTOR_TYPE;

TRUNCATE TABLE VOLT_AMPERE_PROFILE;

TRUNCATE TABLE INJECTOR;

TRUNCATE TABLE TEST_NAME;

TRUNCATE TABLE INJECTOR_TEST;

TRUNCATE TABLE PARAMETERS;

TRUNCATE TABLE VALVES;

TRUNCATE TABLE NOZZLES;

TRUNCATE TABLE APPLICATIONS;

TRUNCATE TABLE CARS;

TRUNCATE TABLE SPARES;

TRUNCATE TABLE ENGINES;

TRUNCATE TABLE REFERENCE;

TRUNCATE TABLE DENSOINJECTORS;

TRUNCATE TABLE ISA_DETECTION;

TRUNCATE TABLE MANUFACTURER_PUMP;

-- TRUNCATE TABLE PUMP;

TRUNCATE TABLE PUMP_TEST_NAME;

TRUNCATE TABLE PUMP_TEST;

TRUNCATE TABLE PUMP_INFO;

TRUNCATE TABLE PUMP_CAR_MODEL;

SET REFERENTIAL_INTEGRITY TRUE;