DROP TABLE IF EXISTS MANUFACTURER;

DROP TABLE IF EXISTS INJECTOR_TYPE;

DROP TABLE IF EXISTS VOLT_AMPERE_PROFILE;

DROP TABLE IF EXISTS INJECTOR;

DROP TABLE IF EXISTS TEST_NAME;

DROP TABLE IF EXISTS INJECTOR_TEST;